### ISSUE TITLE
help with building 

### ISSUE THREAD

**Issue by npreiser** [SamsungARTIK/artik-sdk-js#9]
I am trying to build in a patch,  off the 1.8.3 version.  
When I do a npm rebuild artik-sdk,   a
artik-sdk.node binary appears.  but is dated aug 6th.,   so it does not appear to be building the package.
Does anyone know how to rebuild this , from source.. 
do I need to modify a lock file.. or package file .  ??...  thanks .

**Comment by glemercier** [comment]
@npreiser when you do `npm rebuild ` it is getting the prebuilt version from github because there is a match between the version in `package.json` and prebuilt binaries stored on github.

What you should do to ensure you rebuild from scratch is the following:

```
$ cd <package directory>
$ node-gyp rebuild
```

Another solution is to change the package version in `package.json` for something custom, then `npm rebuild` should rebuild as well.

**Comment by npreiser** [comment]
Thanks,  I have tried both ways , and neither is working ,  both are failing with various errors.

Here is what I am doing on my artik530 , at a dir called <artik>
npm install artik-sdk..
the 1.8.3 version with all dependencies is pulled down as expected,  into a sub directory artik/node_modules
I modify the package.json version in the artik/node_modules/artik-sdk,  to a custom version.. 
Navigate back to artik/node_modules dir.  and do npm rebuild artik-sdk,  
and the below error is what I get

I also tried the node-gyp rebuild , and that too failed. ,   
I am running node version 8.11.3,  
thanks , 
Nick,    


Here is the example of a npm rebuild...





> artik-sdk@1.9.0 install /home/pi/crossplatform_modules/artik/node_modules/artik-sdk
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=8.11.3 runtime=node arch=arm platform=linux)
Package glib-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `glib-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'glib-2.0' found
gyp: Call to 'pkg-config --cflags-only-I glib-2.0' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.113-UNRELEASED
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/crossplatform_modules/artik/node_modules/artik-sdk
gyp ERR! node -v v8.11.3
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! artik-sdk@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the artik-sdk@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-10-19T21_11_18_398Z-debug.log
pi@rvlt-nc-3:~/crossplatform_modules/artik/node_modules$

**Comment by npreiser** [comment]
I got passed the glib-2.0 issue by installing the libglib2.0-dev package..  but now cant get passed a error with the build not finding the libartik-sdk-base package.  even though apt shows that its installed..

**Comment by glemercier** [comment]
You need to install the ARTIK SDK development packages as well:
`$ apt install libartik-sdk-dev`

**Comment by npreiser** [comment]
OK,   thanks for all your help I finally got it built.  
I was missing the build -essentails too.  I thought I had it in my image,  but it got removed...

Question regarding the change to the loop.cc file, which was to correct the cpu utilization bug I found months ago,  ...
Is the change essentially a sleep (wait) call.  I'm concerned that with a longer delay,  I not going to get 
as quick adc reads.,  gpio polling as I may need in the future.  
Does this effect the speed that I can poll....?

**Comment by glemercier** [comment]
We added a 1ms sleep to avoid calling the loop too frequently, which would generate the high CPU load you saw in the first place. It might have an effect on the reactivity of your polling mechanisms indeed, but we believe it should be to an acceptable extent, and in such non-RT systems you don't get time measurement accuracy below the millisecond anyway.

Also we believe GPIO polling should be avoided since we provide interrupt-based events, and if you need to have sub-millisecond accuracy for some hardware access (like ADC or GPIO), such high-level JS APIs are probably not suitable anyway.

If this patch affects proper function or your application for some reason, we are open to discussing your use case and find potential solutions. In the meantime it should be harmless for general use and most applications.
